"""
  EventLogging
  ~~~~~~~~~~~~

  This module contains scripts for processing streams of events
  generated by EventLogging, a MediaWiki extension for logging
  structured data from client-side code.

  For information on how to install and use this module, please see:
  http://www.mediawiki.org/wiki/Extension:EventLogging

  :copyright: (c) 2012 by Ori Livneh
  :license: GNU General Public Licence 2.0 or later

"""
from setuptools import setup


setup(
    name='eventlogging',
    version='0.4',
    license='GPL',
    author='Ori Livneh',
    author_email='ori@wikimedia.org',
    url='www.mediawiki.org/wiki/Extension:EventLogging'
    description='Server-side component of EventLogging MediaWiki extension.',
    long_description=__doc__,
    packages=(
        'eventlogging',
    ),
    scripts=(
        'bin/log2json.py',
        'bin/reflect.py',
        'bin/seqmon.py',
        'bin/udp2zmq.py',
        'bin/zmq2log.py'
    ),
    install_requires=(
        "pyzmq >= 2.1",
        "jsonschema >= 0.7"
    ),
)
